bufferoverflow bugfix
HPDCS/ROOT-Sim pull request #38
Opened 2017-01-30 11:49 UTC by ael-code

the `statistics_post_lp_data` expect a lid as first parameter
but a gid was used instead. This led to a bufferoverflow.

The first commit is a minor bugfix

2017-02-08 18:50 UTC, alessandropellegrini requested changes

2017-02-08 18:50 UTC, alessandropellegrini commented on src/queues/queues.c
> +							       F_EQUAL(LPS[lid_receiver]->bound->timestamp, msg_to_process->timestamp)){
`simtime_t` is a `double`, so the correct macro should be `D_EQUALS`

2017-02-08 18:50 UTC, alessandropellegrini commented on src/queues/queues.c
> +							   F_EQUAL(LPS[lid_receiver]->bound->timestamp, msg_to_process->timestamp)){
`D_EQUALS` as well

2017-02-09 10:47 UTC, ael-code commented on src/queues/queues.c
> +							       F_EQUAL(LPS[lid_receiver]->bound->timestamp, msg_to_process->timestamp)){
ah.. sorry I was confused by the compiler warning :)
```
warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
```

2017-02-09 10:47 UTC, ael-code commented on src/queues/queues.c
> +							   F_EQUAL(LPS[lid_receiver]->bound->timestamp, msg_to_process->timestamp)){
Solved in the new commits as well

2017-02-09 10:47 UTC, ael-code commented on src/queues/queues.c
> +							       F_EQUAL(LPS[lid_receiver]->bound->timestamp, msg_to_process->timestamp)){
Solved in the new commits

2017-02-09 11:15 UTC, alessandropellegrini approved these changes

2017-02-09 11:24 UTC, merged